version: "3.8"

services:
  # PostgresSQL
  db:
    image: postgres:16.2
    environment:
      TZ: Asia/Tokyo
      PGTZ: Asia/Tokyo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
volumes:
  db: